# Generated by Django 4.1.1 on 2022-10-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolbus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('district', models.CharField(max_length=36)),
                ('community', models.CharField(max_length=36)),
                ('county', models.CharField(max_length=36)),
                ('state', models.CharField(max_length=36)),
            ],
            options={
                'verbose_name_plural': 'Schoolbuses',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('school_type', models.CharField(choices=[('1', 'Kindergarten'), ('2', 'Preschool'), ('3', 'K-12'), ('4', 'Middle School'), ('5', 'High School')], max_length=36)),
                ('address', models.CharField(max_length=36)),
                ('city', models.CharField(max_length=36)),
                ('state', models.CharField(max_length=36)),
                ('zip', models.CharField(max_length=36)),
                ('phone', models.CharField(max_length=36)),
                ('principle', models.CharField(max_length=36)),
                ('school_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolbus.schoolbus')),
            ],
        ),
    ]
